# Generated by Django 3.1 on 2020-12-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsolution',
            name='question',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='addsolution',
            name='solution',
            field=models.CharField(max_length=50),
        ),
    ]
