# Generated by Django 3.1 on 2020-12-20 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201220_0510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addsolution',
            new_name='solution',
        ),
    ]
